# Generated by Django 3.1.7 on 2021-06-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=20)),
                ('candidate_email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='test_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_round', models.IntegerField()),
                ('second_round', models.IntegerField()),
                ('third_round', models.IntegerField()),
                ('total', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jksds', to='tast_app.candidatedata')),
            ],
        ),
    ]
